blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/zeroblackalpha/antimuon/discussions
    about: Please ask and answer general questions here.
  - name: Security Bugs
    about: Please contact zeroblackalpha directly!