name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          architecture: x64
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Install node dependencies
        run: npm ci
        working-directory: frontend
      #- run: npm test
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Cache go modules
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache
          path: |
            ~/go/pkg/mod
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: go test ./...
      - name: Run Wails
        run: wails build -platform windows/amd64,linux/amd64,darwin/amd64
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: antimuon
          path: build/bin
