name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: web
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        architecture:
          - x64
        # an extra run:
        # include:
          #- os: windows-latest
          #  architecture: x64
    name: Build Frontend - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          architecture: ${{ matrix.architecture }}
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'
      - run: npm ci
      #- run: npm test
