name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    #defaults:
    #  run:
    #    working-directory: web
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        architecture:
          - x64
        # an extra run:
        # include:
        #  - os: windows-latest
        #    architecture: x64
    name: Build - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          architecture: ${{ matrix.architecture }}
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'
      - name: Install node dependencies
        run: npm ci
        working-directory: web
      - name: Build frontend
        run: npm run build
        working-directory: web
      #- run: npm test
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Install webview dependencies
        run: sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev
        if: ${{ matrix.os == ubuntu-latest }}
      - name: Cache go modules
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: go test ./...
